apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        -  image: yakhub4881/myapp:1.0
           name: myapp-container
           ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 32000
  selector:
    app: myapp
